#!/usr/bin/env bats
#
# Encryption Tests
#

#
# Load environment variables - these are automatically
# generated by a grunt task
#
load credentials

@test "Check environment" {
    run "$BATSDIR"/set2/test0.sh
    [ "$status" -eq 0 ]
}

@test "Incorrect user id" {
    run "$BATSDIR"/set2/test1.sh
    [ "$status" -eq 0 ]
}

@test "Incorrect user token" {
    run "$BATSDIR"/set2/test2.sh
    [ "$status" -eq 0 ]
}

@test "SR_set incomplete args" {
    run "$BATSDIR"/set2/test4.sh
    [ "$status" -eq 0 ]
}

@test "SR_set invalid reply flag" {
    run "$BATSDIR"/set2/test5.sh
    [ "$status" -eq 0 ]
}

@test "SR_send incomplete args" {
    run "$BATSDIR"/set2/test6.sh
    [ "$status" -eq 0 ]
}

@test "SR_set job not started" {
    run "$BATSDIR"/set2/test7.sh
    [ "$status" -eq 0 ]
}

@test "Send simple content and text file" {
    run "$BATSDIR"/set2/test8.sh
    [ "$status" -eq 0 ]
}

@test "Simple unicode" {
    run "$BATSDIR"/set2/test9.sh
    [ "$status" -eq 0 ]
}

@test "Slash in project name" {
    run "$BATSDIR"/set2/test10.sh
    [ "$status" -eq 0 ]
}

@test "Slash in location name" {
    run "$BATSDIR"/set2/test11.sh
    [ "$status" -eq 0 ]
}

@test "Simple reply" {
    run "$BATSDIR"/set2/test12.sh
    [ "$status" -eq 0 ]
}

@test "Spaces in names" {
    run "$BATSDIR"/set2/test14.sh
    [ "$status" -eq 0 ]
}

@test "png file" {
    run "$BATSDIR"/set2/test15.sh
    [ "$status" -eq 0 ]
}

@test "Backtick in project name" {
    run "$BATSDIR"/set2/test16.sh
    [ "$status" -eq 0 ]
}

@test "Backtick in location name" {
    run "$BATSDIR"/set2/test17.sh
    [ "$status" -eq 0 ]
}

@test "Dollar and allowed backtick in literal args" {
    run "$BATSDIR"/set2/test18.sh
    [ "$status" -eq 0 ]
}

@test "Variables as args with values including dollar, space, backtick" {
    run "$BATSDIR"/set2/test19.sh
    [ "$status" -eq 0 ]
}

@test "svg file" {
    run "$BATSDIR"/set2/test20.sh
    [ "$status" -eq 0 ]
}

@test "Commas in names" {
    run "$BATSDIR"/set2/test21.sh
    [ "$status" -eq 0 ]
}

@test "Commas in names" {
    run "$BATSDIR"/set2/test22.sh
    [ "$status" -eq 0 ]
}


@test "Colons in names" {
    run "$BATSDIR"/set2/test24.sh
    [ "$status" -eq 0 ]
}

@test "Multiple reply content entries" {
    run "$BATSDIR"/set2/test25.sh
    [ "$status" -eq 0 ]
}

@test "Double quote in project name" {
    run "$BATSDIR"/set2/test26.sh
    [ "$status" -eq 0 ]
}

@test "Double quote in SR_set name" {
    run "$BATSDIR"/set2/test27.sh
    [ "$status" -eq 0 ]
}

@test "Double quote in location name" {
    run "$BATSDIR"/set2/test28.sh
    [ "$status" -eq 0 ]
}

@test "Single quote in project name" {
    run "$BATSDIR"/set2/test29.sh
    [ "$status" -eq 0 ]
}

@test "Single quote in SR_set name" {
    run "$BATSDIR"/set2/test30.sh
    [ "$status" -eq 0 ]
}

@test "Single quote in location name" {
    run "$BATSDIR"/set2/test31.sh
    [ "$status" -eq 0 ]
}

@test "Backslash in project name" {
    run "$BATSDIR"/set2/test32.sh
    [ "$status" -eq 0 ]
}

@test "Backslash in SR_set name" {
    run "$BATSDIR"/set2/test33.sh
    [ "$status" -eq 0 ]
}

@test "Backslash in location name" {
    run "$BATSDIR"/set2/test34.sh
    [ "$status" -eq 0 ]
}

@test "Add job to existing project" {
    run "$BATSDIR"/set2/test35.sh
    [ "$status" -eq 0 ]
}

@test "Add job to shared project" {
    run "$BATSDIR"/set2/test36.sh
    [ "$status" -eq 0 ]
}

@test "Multiple content items and files" {
    run "$BATSDIR"/set2/test37.sh
    [ "$status" -eq 0 ]
}

@test "Reply test with browser-encrypted data" {
    run "$BATSDIR"/set2/test38.sh
    [ "$status" -eq 0 ]
}

@test "Projects with same plain name, different passphrases" {
    run "$BATSDIR"/set2/test39.sh
    [ "$status" -eq 0 ]
}

@test "Simple utf8" {
    run "$BATSDIR"/set2/test40.sh
    [ "$status" -eq 0 ]
}

@test "Add jobs to multiple existing projects" {
    run "$BATSDIR"/set2/test41.sh
    [ "$status" -eq 0 ]
}

@test "Encrypted and unencrypted projects with same plaintext name" {
    run "$BATSDIR"/set2/test42.sh
    [ "$status" -eq 0 ]
}

@test "Try to access shared project with invalid email" {
    run "$BATSDIR"/set2/test43.sh
    [ "$status" -eq 0 ]
}

@test "Try to add job to shared project with no permission" {
    run "$BATSDIR"/set2/test44.sh
    [ "$status" -eq 0 ]
}

@test "Try to add job to shared project with read permission" {
    run "$BATSDIR"/set2/test45.sh
    [ "$status" -eq 0 ]
}

@test "Try to add job to shared project with reply permission" {
    run "$BATSDIR"/set2/test46.sh
    [ "$status" -eq 0 ]
}

@test "Try to add job to shared project with wrong passphrase" {
    run "$BATSDIR"/set2/test47.sh
    [ "$status" -eq 0 ]
}

@test "Encrypted and unencrypted projects with same plaintext name" {
    run "$BATSDIR"/set2/test48.sh
    [ "$status" -eq 0 ]
}


@test "Try to modify sharing of non-owned project" {
    run "$BATSDIR"/set2/test49.sh
    [ "$status" -eq 0 ]
}
