#!/usr/bin/env bats
#
# Data Limit Tests
#

#
# Load environment variables - these are automatically
# generated by a grunt task
#
load credentials

@test "Test limit SR_PROJECTS_PER_USER" {
    run "$BATSDIR"/set3/test1.sh
    [ "$status" -eq 0 ]
}

@test "Test limit SR_JOBS_PER_PROJECT" {
    run "$BATSDIR"/set3/test2.sh
    [ "$status" -eq 0 ]
}

@test "Test limit SR_LOCATIONS_PER_JOB" {
    run "$BATSDIR"/set3/test3.sh
    [ "$status" -eq 0 ]
}

@test "Test limit SR_MESSAGES_PER_LOCATION" {
    run "$BATSDIR"/set3/test4.sh
    [ "$status" -eq 0 ]
}

@test "Test limit SR_MESSAGE_SIZE" {
    run "$BATSDIR"/set3/test5.sh
    [ "$status" -eq 0 ]
}

@test "Test limit SR_MESSAGE_SIZE_PER_JOB" {
    run "$BATSDIR"/set3/test6.sh
    [ "$status" -eq 0 ]
}
